export default defineEventHandler(async (event) => {
    const { req, res } = event;
    res.statusCode = 200;
    return [{
        locale:'vi-VN',
        data:[
            {
                "title": "Cải Tạo Khu Nghỉ Dưỡng Anlam Saigon River ở Việt Nam",
                "src": "/image/project/pages/pro1.jpg",
                "pdate": "10 tháng 3, 2022",
                "desc": "An Lam Retreats Saigon River hoạt động theo phong cách mới sau khi cải tạo, kết hợp trải nghiệm nghỉ dưỡng với thiên nhiên, truyền thống và phục hồi sức khỏe tinh thần."
            },
            {
                "title": "Tái Kích Hoạt Địa Điểm Ngành Công Nghiệp Khách Sạn",
                "src": "/image/project/pages/pro2.jpg",
                "pdate": "8 tháng 3, 2022",
                "desc": "Do hạn chế đi lại toàn cầu để kiểm soát dịch bệnh Coronavirus, ngành công nghiệp khách sạn đang đối mặt với viễn cảnh u ám."
            },
            {
                "title": "Các Khách Sạn ở Châu Mỹ Cần 11,75 Tỷ USD Đầu Tư vào Nội Thất và Thiết Bị",
                "src": "/image/project/pages/pro3.jpg",
                "pdate": "2 tháng 3, 2022",
                "desc": "Các khoản đầu tư vào khách sạn 5 sao chiếm 7,36 tỷ USD cho nội thất và thiết bị, trong khi các dự án 4 sao chiếm 4,39 tỷ USD."
            },
            {
                "title": "[2022] Năm Du Lịch Tại Hoa Kỳ Phục Hồi Mạnh Mẽ",
                "src": "/image/project/pages/pro4.jpg",
                "pdate": "24 tháng 2, 2022",
                "desc": "Sự trở lại của du lịch như một nguồn kinh tế quan trọng sau gần 2 năm hỗn loạn."
            },
            {
                "title": "Thiết Kế Nội Thất Trong Các Khái Niệm Hiện Đại",
                "src": "/image/project/pages/pro5.jpg",
                "pdate": "18 tháng 2, 2022",
                "desc": "Ba loại thiết kế nội thất hiện đại: Chức năng hiện đại; Chuyển tiếp hiện đại, thường được biết đến là đương đại; và Đương đại thương mại, còn được gọi là “Borax”."
            },
            {
                "title": "Ngày Tưởng Niệm Nghề Thủ Công và Công Nghiệp Gỗ năm 2022",
                "src": "/image/project/pages/pro6.jpg",
                "pdate": "15 tháng 2, 2022",
                "desc": "Theo truyền thống, ngày tưởng niệm năm 2022 xoay quanh chủ đề “Kết Nối Hy Vọng”. Tran Duc Furnishings tự hào là nhà tài trợ vàng cho ngày tưởng niệm năm nay."
            },
            {
                "title": "Thời Đại Cải Tạo Khách Sạn Trong Thế Kỷ 21",
                "src": "/image/project/pages/pro7.jpg",
                "pdate": "18 tháng 1, 2022",
                "desc": "Trong ngành khách sạn, dự án cải tạo khách sạn nhằm nâng cao trải nghiệm khách hàng, tăng độ bền và giảm chi phí vận hành."
            },
            {
                "title": "Bàn Khách Sạn Sang Trọng Tại Nhà Máy Nội Thất Là Gì?",
                "src": "/image/project/pages/pro8.jpg",
                "pdate": "14 tháng 1, 2022",
                "desc": "Chỉ có một số ít thiết kế bàn khách sạn sang trọng có khả năng giúp khách sạn của bạn nổi bật. Tran Duc Furnishings sản xuất nội thất theo yêu cầu."
            },
            {
                "title": "Nội Thất Đô Thị Giúp Khách Sạn Nổi Bật",
                "src": "/image/project/pages/pro9.jpg",
                "pdate": "12 tháng 1, 2022",
                "desc": "Ý tưởng chính là chuyển đổi các nhà kho để tạo khu vực lưu trú. Tuy nhiên, sẽ rất tuyệt vời khi tường gạch lộ kết hợp với nội thất thanh lịch và tinh tế."
            },
            {
                "title": "Khách Sạn Omni Oklahoma City Minh Họa Định Nghĩa 4 Sao Mới",
                "src": "/image/project/pages/pro10.jpg",
                "pdate": "7 tháng 1, 2022",
                "desc": "Khách sạn Omni có 605 phòng, bao gồm 29 phòng suite. Nội thất mang phong cách hiện đại với chi tiết tinh tế và chút cổ điển, tạo nên nơi nghỉ dưỡng tinh tế."
            },
            {
                "title": "Danh Sách Nội Thất Khách Sạn Trong Phòng Sang Trọng [Phần Mở Rộng]",
                "src": "/image/project/pages/pro11.jpg",
                "pdate": "16 tháng 12, 2021",
                "desc": "Khách sạn luôn cố gắng tạo ra nhiều ưu đãi hơn để nâng cao trải nghiệm khách hàng. Điều đó dẫn đến các phần mở rộng của nội thất khách sạn."
            },
            {
                "title": "Đầu Giường & Đế Giường Khách Sạn",
                "src": "/image/project/pages/pro12.jpg",
                "pdate": "13 tháng 12, 2021",
                "desc": "Khu vực ngủ bao gồm đầu giường và đế giường khách sạn. Nhà máy của chúng tôi đã sản xuất rất nhiều nội thất cho ngành khách sạn sang trọng."
            }
        ],
        data2:[
                {
                    "title": "Khách Sạn Sheraton Waikiki Sau Khi Được Cải Tạo",
                    "src": "/image/project/pages/pro13.jpg",
                    "pdate": "10 tháng 12, 2021",
                    "desc": "Khách sạn 50 tuổi này có hơn 1600 phòng, tất cả đều đã được cải tạo mới. Tranducfurnishings hân hạnh là một phần trong dự án cải tạo khách sạn này với vai trò là nhà sản xuất nội thất."
                },
                {
                    "title": "Tủ Đồ & Tủ Quần Áo Khách Sạn",
                    "src": "/image/project/pages/pro14.jpg",
                    "pdate": "6 tháng 12, 2021",
                    "desc": "Phần lưu trữ đóng vai trò quan trọng trong trải nghiệm khách hàng. Tủ quần áo khách sạn đảm nhiệm vai trò lưu trữ chính."
                },
                {
                    "title": "Cách MDF Trở Nên Phổ Biến Trong Nội Thất Khách Sạn",
                    "src": "/image/project/pages/pro15.jpg",
                    "pdate": "2 tháng 12, 2021",
                    "desc": "Ngành nội thất khách sạn sang trọng đang dẫn đầu xu hướng sử dụng ván MDF trong sản xuất nội thất."
                },
                {
                    "title": "The Ritz-Carlton, Amelia Island Thể Hiện Cách Khu Nghỉ Dưỡng 5 Sao Hoạt Động",
                    "src": "/image/project/pages/pro16.jpg",
                    "pdate": "29 tháng 11, 2021",
                    "desc": "Chúng tôi liên tục cung cấp giải pháp cho dự án nội thất khách sạn sang trọng dựa trên các yêu cầu về chất liệu. Tranducfurnishings tự hào sản xuất các sản phẩm nội thất cho thương hiệu The Ritz-Carlton."
                },
                {
                    "title": "Lớp Phủ Bốc Hơi Vật Lý (PVD) Trong Nội Thất Khách Sạn",
                    "src": "/image/project/pages/pro17.jpg",
                    "pdate": "27 tháng 11, 2021",
                    "desc": "Tranducfurnishings cung cấp các vật liệu chất lượng cao với nhiều phương pháp phủ. Chúng tôi đẩy mạnh năng lực sản xuất nội bộ bằng cách đầu tư vào công nghệ phủ PVD theo yêu cầu của khách hàng."
                },
                {
                    "title": "Khách Sạn Four Seasons One Dalton Định Nghĩa Tiêu Chuẩn Sang Trọng [5 Sao]",
                    "src": "/image/project/pages/pro18.jpg",
                    "pdate": "18 tháng 11, 2021",
                    "desc": "Nội thất khách sạn được sản xuất nổi bật trong bối cảnh phong cảnh nhìn từ trên cao. Tranducfurnishings tự hào là nhà sản xuất nội thất khách sạn đạt tiêu chuẩn sang trọng của Four Seasons."
                },
                {
                    "title": "AAA Five-Diamond – Đánh Giá Tiêu Chuẩn Sang Trọng Khách Sạn",
                    "src": "/image/project/pages/pro19.jpg",
                    "pdate": "15 tháng 11, 2021",
                    "desc": "Trong tiêu chuẩn sang trọng, khách sạn 5 sao và 5 kim cương mang đến trải nghiệm hoàn hảo cho khách hàng. Chỉ có 0,3% trong số 60.000 điểm đến được AAA kiểm định đạt danh hiệu Five Diamond."
                },
                {
                    "title": "Danh Sách Nội Thất Khách Sạn Trong Phòng Sang Trọng [Chức Năng Lưu Trữ]",
                    "src": "/image/project/pages/pro20.jpg",
                    "pdate": "12 tháng 11, 2021",
                    "desc": "Chức năng lưu trữ luôn là điểm nhấn trong các khách sạn sang trọng nhằm nâng cao trải nghiệm của khách hàng. Một vài danh mục chính được liệt kê dưới đây."
                },
                {
                    "title": "Khách Sạn Sheraton [Sở Hữu Bởi Marriott]",
                    "src": "/image/project/pages/pro21.jpg",
                    "pdate": "10 tháng 11, 2021",
                    "desc": "Khách sạn Sheraton nổi bật với thiết kế nội thất hiện đại và không gian rộng lớn. Tranducfurnishings rất hân hạnh là nhà sản xuất nội thất cho Sheraton."
                },
                {
                    "title": "Phong Cách Trang Trí Khách Sạn Lấy Cảm Hứng Từ Vùng Nông Thôn",
                    "src": "/image/project/pages/pro22.jpg",
                    "pdate": "5 tháng 11, 2021",
                    "desc": "Phong cách trang trí khách sạn lấy cảm hứng từ vùng nông thôn đang trở nên phổ biến trong các khu nghỉ dưỡng và khách sạn ven đô thị."
                },
                {
                    "title": "Các Yếu Tố Quyết Định Thành Công Trong Nội Thất Khách Sạn",
                    "src": "/image/project/pages/pro23.jpg",
                    "pdate": "1 tháng 11, 2021",
                    "desc": "Những yếu tố như tính bền vững, thiết kế thân thiện với môi trường và không gian thoải mái giúp cải thiện trải nghiệm của khách hàng trong các dự án nội thất khách sạn."
                },
                {
                    "title": "Các Thành Phần Nội Thất Thân Thiện Với Khách Sạn",
                    "src": "/image/project/pages/pro24.jpg",
                    "pdate": "30 tháng 10, 2021",
                    "desc": "Tranducfurnishings tự hào cung cấp nội thất bền vững, thân thiện với khách sạn và môi trường. Những thiết kế nội thất thân thiện với khách sạn góp phần tạo nên trải nghiệm nghỉ dưỡng thoải mái cho khách hàng."
                }
        ],
        data3:[
            {title:"Golden Nugget Lake Charles",location:"2550 Đại lộ Golden Nugget, Lake Charles",id:'Golden',
                img:[{src:'/image/project/detailProducts/Golden/product1.jpg'},
                    {src:'/image/project/detailProducts/Golden/product2.jpg'},
                    {src:'/image/project/detailProducts/Golden/product3.jpg'}
                ]},
            {title:"Renaissance Richardson",location:"900 E Lookout Dr, Richardson, TX 75082, Hoa Kỳ",id:'Renaissance',
                img:[{src:'/image/project/detailProducts/Renaissance/product1.jpg'},
                     {src:'/image/project/detailProducts/Renaissance/product2.jpg'},
                     {src:'/image/project/detailProducts/Renaissance/product3.jpg'},
                     {src:'/image/project/detailProducts/Renaissance/product4.jpg'},
                     {src:'/image/project/detailProducts/Renaissance/product5.jpg'},
                     {src:'/image/project/detailProducts/Renaissance/product6.jpg'},
                     {src:'/image/project/detailProducts/Renaissance/product7.jpg'}
                ]},
                {title:"Hyatt Centric Fishermans Wharf",location:"555 North Point St, San Francisco, CA 94133, Hoa Kỳ",id:'Hyatt',
                    img:[{src:'/image/project/detailProducts/Hyatt/product1.jpg'},
                         {src:'/image/project/detailProducts/Hyatt/product2.jpg'},
                         {src:'/image/project/detailProducts/Hyatt/product3.jpg'},
                         {src:'/image/project/detailProducts/Hyatt/product4.jpg'},
                         {src:'/image/project/detailProducts/Hyatt/product5.jpg'},
                         {src:'/image/project/detailProducts/Hyatt/product6.jpg'},
                    ]},
                {title:"Kimpton Charlotte",location:"303 S Church St, Charlotte, North Carolina 28202, Hoa Kỳ",id:'Kimpton',
                    img:[{src:'/image/project/detailProducts/Kimpton/product1.jpg'},
                         {src:'/image/project/detailProducts/Kimpton/product2.jpg'},
                         {src:'/image/project/detailProducts/Kimpton/product3.jpg'},
                         {src:'/image/project/detailProducts/Kimpton/product4.jpg'},
                         {src:'/image/project/detailProducts/Kimpton/product5.jpg'},
                         {src:'/image/project/detailProducts/Kimpton/product6.jpg'},
                         {src:'/image/project/detailProducts/Kimpton/product7.jpg'},
                    ]},
                {title:"Beekman new york hotel room",location:"123 Nassau St, New York, NY 10038, Hoa Kỳ",id:'Beekman',
                    img:[{src:'/image/project/detailProducts/Beekman/product1.jpg'},
                         {src:'/image/project/detailProducts/Beekman/product2.jpg'},
                         {src:'/image/project/detailProducts/Beekman/product3.jpg'},
                         {src:'/image/project/detailProducts/Beekman/product4.jpg'},
                    ]},
                {title:"Line Dc Hotel",location:"1770 Euclid St NW, Washington, DC 20009, Hoa Kỳ",id:'Line',
                    img:[{src:'/image/project/detailProducts/Line/product1.jpg'},
                        {src:'/image/project/detailProducts/Line/product2.jpg'},
                        {src:'/image/project/detailProducts/Line/product3.jpg'},
                        {src:'/image/project/detailProducts/Line/product4.jpg'},
                        {src:'/image/project/detailProducts/Line/product5.jpg'},
                        {src:'/image/project/detailProducts/Line/product6.jpg'},
                    ]},
                {title:"Fairmont Claremont",location:"41 Tunnel Rd, Berkeley, CA 94705, Hoa Kỳ",id:'Fairmont',
                    img:[{src:'/image/project/detailProducts/Fairmont/product1.jpg'},
                        {src:'/image/project/detailProducts/Fairmont/product2.jpg'},
                        {src:'/image/project/detailProducts/Fairmont/product3.jpg'},
                        {src:'/image/project/detailProducts/Fairmont/product4.jpg'},
                        {src:'/image/project/detailProducts/Fairmont/product5.jpg'},
                    ]},
                {title:"Marriott Dallas Texas",location:"650 North Pearl Street, Dallas, Texas 75201, Hoa Kỳ",id:'Marriott',
                    img:[{src:'/image/project/detailProducts/Marriott/product1.jpg'},
                        {src:'/image/project/detailProducts/Marriott/product2.jpg'},
                        {src:'/image/project/detailProducts/Marriott/product3.jpg'},
                    ]},
                {title:"Conrad Miami",location:"1395 Brickell Ave, Miami, FL 33131, Hoa Kỳ",id:'Conrad',
                    img:[{src:'/image/project/detailProducts/Conrad/product1.jpg'},
                        {src:'/image/project/detailProducts/Conrad/product2.jpg'},
                        {src:'/image/project/detailProducts/Conrad/product3.jpg'},
                        {src:'/image/project/detailProducts/Conrad/product4.jpg'},
                        {src:'/image/project/detailProducts/Conrad/product5.jpg'},
                        {src:'/image/project/detailProducts/Conrad/product6.jpg'},
                        {src:'/image/project/detailProducts/Conrad/product7.jpg'},
                        {src:'/image/project/detailProducts/Conrad/product8.jpg'},
                    ]},
                {title:"Tampa Marriott Waterside",location:"505 Water St, Tampa, FL 33602, Hoa Kỳ",id:'Tampa',
                    img:[{src:'/image/project/detailProducts/Tampa/product1.jpg'},
                        {src:'/image/project/detailProducts/Tampa/product2.jpg'},
                        {src:'/image/project/detailProducts/Tampa/product3.jpg'},
                        {src:'/image/project/detailProducts/Tampa/product4.jpg'},
                        {src:'/image/project/detailProducts/Tampa/product5.jpg'},
                        {src:'/image/project/detailProducts/Tampa/product6.jpg'},
                    ]},
                {title:"Godfrey Illinois",location:"127 W Huron Street, Chicago, IL, 60654, Hoa Kỳ",id:'Godfrey',
                    img:[{src:'/image/project/detailProducts/Godfrey/product1.jpg'},
                        {src:'/image/project/detailProducts/Godfrey/product2.jpg'},
                        {src:'/image/project/detailProducts/Godfrey/product3.jpg'},
                        {src:'/image/project/detailProducts/Godfrey/product4.jpg'},
                        {src:'/image/project/detailProducts/Godfrey/product5.jpg'},
                    ]},
                {title:"Hilton Grand Islander @",location:"2023 Kalia Road, Honolulu, Hawaii 96815, Hoa Kỳ",id:'Hilton',
                    img:[{src:'/image/project/detailProducts/Hilton/product1.jpg'},
                        {src:'/image/project/detailProducts/Hilton/product2.jpg'},
                    ]},
        ],
        data4: [
            {alt: 'king1', id: 'king1', name: 'Bộ giường khách sạn King Room', minPrice: 315, maxPrice: 545,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/king1/king1.jpg'},
                      {src: '/image/ReferencePrice/BedBase/Detail/king1/king2.jpg'},
                      {src: '/image/ReferencePrice/BedBase/Detail/king1/king3.jpg'},
                      {src: '/image/ReferencePrice/BedBase/Detail/king1/king4.jpg'}
                ]
            },
            {alt: 'king2', id: 'king2', name: 'Bộ giường khách sạn - Đầu giường và chân giường', minPrice: 275, maxPrice: 495,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/king2.jpg'}]
            },
            {alt: 'king3', id: 'king3', name: 'Bộ giường khách sạn - Đầu giường và chân giường', minPrice: 345, maxPrice: 575,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/king3.jpg'}]
            },
            {alt: 'king4', id: 'king4', name: 'Bộ giường khách sạn - Đầu giường và chân giường', minPrice: 295, maxPrice: 615,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/king4.jpg'}]
            },
            {alt: 'king5', id: 'king5', name: 'Đầu giường King - Khách sạn Hilton Myrtle Beach Resort', minPrice: 345, maxPrice: 525,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/king5.jpg'}]
            },
            {alt: 'king6', id: 'king6', name: 'Đầu giường King - Suite cao cấp Hyatt Regency Morristown', minPrice: 445, maxPrice: 765,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/king6.jpg'}]
            },
            {alt: 'king7', id: 'king7', name: 'Đầu giường King', minPrice: 275, maxPrice: 535,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/king7.jpg'}]
            },
            {alt: 'king8', id: 'king8', name: 'Đầu giường King - Choctaw Durant', minPrice: 345, maxPrice: 625,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/king8.jpg'}]
            },
            {alt: 'king9', id: 'king9', name: 'Đầu giường King', minPrice: 315, maxPrice: 555,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/king10.jpg'}]
            },
            {alt: 'king11', id: 'king11', name: 'Đầu giường King', minPrice: 245, maxPrice: 550,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/king11.jpg'}]
            },
            {alt: 'king12', id: 'king12', name: 'Đầu giường King - 54117', minPrice: 145, maxPrice: 425,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/king12.jpg'}]
            },
            {alt: 'queen1', id: 'queen1', name: 'Đầu giường đôi Queen', minPrice: 345, maxPrice: 715,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/queen1.jpg'}]
            },
            {alt: 'queen2', id: 'queen2', name: 'Đầu giường đôi Queen', minPrice: 365, maxPrice: 735,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/queen2.jpg'}]
            },
            {alt: 'queen3', id: 'queen3', name: 'Đầu giường đôi Queen', minPrice: 345, maxPrice: 675,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/queen3.jpg'}]
            },
            {alt: 'queen4', id: 'queen4', name: 'Đầu giường đôi Queen', minPrice: 365, maxPrice: 745,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/queen4.jpg'}]
            },
            {alt: 'queen5', id: 'queen5', name: 'Đầu giường đôi Queen', minPrice: 335, maxPrice: 755,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/queen5.jpg'}]
            },
            {alt: 'queen6', id: 'queen6', name: 'Đầu giường đôi Queen', minPrice: 375, maxPrice: 725,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/queen6.jpg'}]
            },
            {alt: 'bed1', id: 'bed1', name: 'Bộ giường khách sạn', minPrice: 645, maxPrice: 955,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/bed1.jpg'}]
            },
            {alt: 'bed2', id: 'bed2', name: 'Bộ giường khách sạn - Đầu giường và chân giường', minPrice: 635, maxPrice: 955,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/bed2.jpg'}]
            },
            {alt: 'bed3', id: 'bed3', name: 'Bộ giường khách sạn - Đầu giường và phòng ngủ', minPrice: 625, maxPrice: 875,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/bed3.jpg'}]
            },
            {alt: 'bed4', id: 'bed4', name: 'Bộ giường khách sạn - Đầu giường và chân giường', minPrice: 750, maxPrice: 1150,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/bed4.jpg'}]
            },
            {cabinet: []},
            {closet: []},
            {tv: []},
            {nightstand: []},
            {table: []},
            {sofa: []},
            {vanity: []}
        ]
        },
        {
        locale:'en-US',
        data:[
            {"title": "The Renovation Of Anlam Saigon River Resort in Vietnam",
             "src": "/image/project/pages/pro1.jpg",
             "pdate":"March 10, 2022",
             "desc":"An Lam Retreats Saigon River runs a new style after renovation as blending resort experience with nature, traditions, and restoring mental health. "
            },
            {"title": "Reactivating The Hospitality Industry’s Locus",
             "src": "/image/project/pages/pro2.jpg",
             "pdate":"March 8, 2022",
             "desc":"The worldwide travel restrictions imposed to help control the Coronavirus epidemic, the hospitality industry has been facing grim prospects",
            },
            {"title": "Hotels in The Americas Will Require $11.75 Billion in Furniture and Equipment",
             "src": "/image/project/pages/pro3.jpg",
             "pdate":"March 2, 2022",
             "desc":"The five-star investments account for $7.36 billion in furniture and equipment, while the four-star projects account for $4.39 billion.",
            },
            {"title": "[2022] The Year, Tourism In The United States Will Recover Dramatically",
             "src": "/image/project/pages/pro4.jpg",
             "pdate":"February 24, 2022",
             "desc":"The return of tourism as a significant economic generators after nearly 2 years of chaos.",
            },
            {"title": "Furniture Design In Modern Concepts",
             "src": "/image/project/pages/pro5.jpg",
             "pdate":"February 18, 2022",
             "desc":"Three types of modern furniture design: Functionalist Modern; Transitional Modern, which has become known as contemporary; and Commercial contemporary, termed “Borax”",
            },
            {"title": "The Commemoration Day of Handicraft and Wood Industry in 2022",
             "src": "/image/project/pages/pro6.jpg",
             "pdate":"February 15, 2022",
             "desc":"Following traditional heritage, the commemoration day of 2022 was oriented around the themes of “Hope Connection”. And Tranducfurnishings was proud to become the Gold Sponsor for the commemoration day of this year.",
            },
            {"title": "The Hotel Renovation Era in The 21st Century",
             "src": "/image/project/pages/pro7.jpg",
             "pdate":"January 18, 2022",
             "desc":"In the hospitality sector, a hotel renovation project attempts to improve the guest experience, enhance durability, and minimize operating costs.",
            },
            {"title": "What is a Luxury Hotel Table in Furniture Factory?",
             "src": "/image/project/pages/pro8.jpg",
             "pdate":"January 14, 2022",
             "desc":"Only a few luxury hotel table designs have the ability to set your hotel apart from the crowd. Tranducfurnishings produce bespoke furniture.",
            },
            {"title": "Urban Interior Makes Hotel Stand Out From The Mess",
             "src": "/image/project/pages/pro9.jpg",
             "pdate":"January 12, 2022",
             "desc":"The basic idea is to transform the warehouses to create accommodation areas. However, it is brilliant when exposed brick walls combine with sleek and elegant furniture.",
            },
            {"title": "Omni Oklahoma City Hotel illustrates A New 4-star Definition",
             "src": "/image/project/pages/pro10.jpg",
             "pdate":"January 7, 2022",
             "desc":"The Omni hotel features 605 rooms, including 29 suites. The interior or furniture contributes a contemporary style with sophisticated details and a little vintage flair that serves as an exquisite retreat. As a hotel furniture producer, Tran Duc Furnishing was involved in the project.",
            },
            {"title": "List Down Hotel Furniture in Luxury Room & Suite [Extension]",
             "src": "/image/project/pages/pro11.jpg",
             "pdate":"December 16, 2021",
             "desc":"Above that, the hotel always attempts to create more offers enhancing the guest experience. That results in extensional parts of hotel furniture.",
            },
            {"title": "Hotel Headboard & Bed base",
             "src": "/image/project/pages/pro12.jpg",
             "pdate":"December 13, 2021",
             "desc":"The sleeping area includes a hotel headboard & bed base. Our factories have generated so many furniture items for the luxury hotel industry.",
        }],
        data2:[
            {"title": "How Sheraton Waikiki Hotel Look Like After Hotel Renovation",
             "src": "/image/project/pages/pro13.jpg",
             "pdate":"December 10, 2021",
             "desc":"The 50-year-old hotel is offering over 1600 rooms, which are all newly renovated. With honor, Tranducfurnishings was a part of the hotel renovation as a hospitality furniture manufacturer in Vietnam.",
            },
            {"title": "Hotel Closet & Wardrobe",
             "src": "/image/project/pages/pro14.jpg",
             "pdate":"December 6, 2021",
             "desc":"Storage Function parts make great guest experience. Hotel Closet & Wardrobe takes main storage role.",
            },
            {"title": "How MDF Become Popular in Hotel Furniture",
             "src": "/image/project/pages/pro15.jpg",
             "pdate":"December 2, 2021",
             "desc":"The luxury hotel furniture industry is leading the trend for applying MDF boards in hospitality furmiture production.",
            },
            {"title": "The Ritz-Carlton, Amelia Island Shows How 5-Star Retreat Performs",
             "src": "/image/project/pages/pro16.jpg",
             "pdate":"November 29, 2021",
             "desc":"We constantly provide solution to luxury hotel furniture project based on their fabric specifications. It is an honor to us. Tran Duc Furnishings factories became places manufacturing luxury hotel furniture items under The Ritz-Carlton Brand.",
            },
            {"title": "Physical Vapor Deposition (PVD) in Hotel Furniture",
             "src": "/image/project/pages/pro17.jpg",
             "pdate":"November 27, 2021",
             "desc":"Tranducfurnishings offer high-quality materials for furnishings with a variety of coating methods. We accelerate in-house production capabilities by investing PVD coating based on clients’ demand.",
            },
            {"title": "Four Seasons Hotel One Dalton Defines Luxury Standard [5-Star]",
             "src": "/image/project/pages/pro18.jpg",
             "pdate":"November 18, 2021",
             "desc":"The hotel furniture was manufactured as a highlight among sky view landscapes. It is an honor to us. Tran Duc Furnishings factories became places manufacturing luxury hotel furniture items under luxury standard of Four Seasons.",
            },
            {"title": "AAA Five-Diamond – How To Evaluate Luxury Hotel Standard",
             "src": "/image/project/pages/pro19.jpg",
             "pdate":"November 15, 2021",
             "desc":"In luxury standard, bold Five-star and Five-Diamond hospitality properties deliver a perfect guest experience. Whereas wealthy travelers actively follow the Five Diamond awards annually, Five Diamond businesses account for only 0.3 percent of the entire 60,000 hospitality destination inspected by AAA. Moreover, the rating list is annually re-evaluated, which means some glorious 5-Diamond hotels will be removed or added.",
            },
            {"title": "List Down Hotel Furniture in Luxury Room & Suite [Storage Function]",
             "src": "/image/project/pages/pro20.jpg",
             "pdate":"November 12, 2021",
             "desc":"Storage Function in Hotel Furniture We all understand the obligatory role of the closet or dresser in the room. Every hotel places a closet in",
            },
            {"title": "Caring & Maintaining Hotel Sofa and Upholstered Furniture Items",
             "src": "/image/project/pages/pro21.jpg",
             "pdate":"November 10, 2021",
             "desc":"We constantly suggest getting luxury hotel upholstered furniture serviced based on their fabric specifications. Hotel operator can almost guarantee that the color of the upholstered furniture",
            },
            {"title": "Materials – Hotel Sofa and Upholstered Items in Luxury Hotel Furniture",
             "src": "/image/project/pages/pro22.jpg",
             "pdate":"November 5, 2021",
             "desc":"It is a different story when the design comes to the manufacturing stage and our technical drawing only supports production.  Many troubles occur. From the",
            },
            {"title": "List Down Hotel Furniture in Luxury Room & Suite [Sleeping Area]",
             "src": "/image/project/pages/pro23.jpg",
             "pdate":"July 30, 2021",
             "desc":"Because guests need more than that as they know they do not stay in their home. Therefore, hotel furniture selection takes the majority role in creating a hotel experience. Here, we list down the furniture parts creating the hotel experience.",
            },
            {"title": "How hotel furniture look luxury",
             "src": "/image/project/pages/pro24.jpg",
             "pdate":"July 21, 2021",
             "desc":"Each high standard hotel obtains unique design and that requires custom-made furniture or bespoke furniture. Their attempt is to brings specialty to travelers, so it is impossible to pick up instance furniture right away from furniture shop next to them.",
            },
        ],
        data3:[
            {title:"Golden Nugget Lake Charles",location:"2550 Golden Nugget Blvd, Lake Charles",id:'Golden',
            img:[{src:'/image/project/detailProducts/Golden/product1.jpg'},
                 {src:'/image/project/detailProducts/Golden/product2.jpg'},
                 {src:'/image/project/detailProducts/Golden/product3.jpg'}
                ]},
            {title:"Renaissance Richardson",location:"900 E Lookout Dr, Richardson, TX 75082, United States",id:'Renaissance',
                img:[{src:'/image/project/detailProducts/Renaissance/product1.jpg'},
                     {src:'/image/project/detailProducts/Renaissance/product2.jpg'},
                     {src:'/image/project/detailProducts/Renaissance/product3.jpg'},
                     {src:'/image/project/detailProducts/Renaissance/product4.jpg'},
                     {src:'/image/project/detailProducts/Renaissance/product5.jpg'},
                     {src:'/image/project/detailProducts/Renaissance/product6.jpg'},
                     {src:'/image/project/detailProducts/Renaissance/product7.jpg'}
                ]},
            {title:"Hyatt Centric Fishermans Wharf",location:"555 North Point St, San Francisco, CA 94133, United States",id:'Hyatt',
                img:[{src:'/image/project/detailProducts/Hyatt/product1.jpg'},
                     {src:'/image/project/detailProducts/Hyatt/product2.jpg'},
                     {src:'/image/project/detailProducts/Hyatt/product3.jpg'},
                     {src:'/image/project/detailProducts/Hyatt/product4.jpg'},
                     {src:'/image/project/detailProducts/Hyatt/product5.jpg'},
                     {src:'/image/project/detailProducts/Hyatt/product6.jpg'},
                ]},
            {title:"Kimpton Charlotte",location:"303 S Church St, Charlotte, North Carolina 28202, United States",id:'Kimpton',
                img:[{src:'/image/project/detailProducts/Kimpton/product1.jpg'},
                     {src:'/image/project/detailProducts/Kimpton/product2.jpg'},
                     {src:'/image/project/detailProducts/Kimpton/product3.jpg'},
                     {src:'/image/project/detailProducts/Kimpton/product4.jpg'},
                     {src:'/image/project/detailProducts/Kimpton/product5.jpg'},
                     {src:'/image/project/detailProducts/Kimpton/product6.jpg'},
                     {src:'/image/project/detailProducts/Kimpton/product7.jpg'},
                ]},
            {title:"Beekman new york hotel room",location:"123 Nassau St, New York, NY 10038, United States",id:'Beekman',
                img:[{src:'/image/project/detailProducts/Beekman/product1.jpg'},
                    {src:'/image/project/detailProducts/Beekman/product2.jpg'},
                    {src:'/image/project/detailProducts/Beekman/product3.jpg'},
                    {src:'/image/project/detailProducts/Beekman/product4.jpg'},
                ]},
            {title:"Line Dc Hotel",location:"1770 Euclid St NW, Washington, DC 20009, United States",id:'Line',
                img:[{src:'/image/project/detailProducts/Line/product1.jpg'},
                    {src:'/image/project/detailProducts/Line/product2.jpg'},
                    {src:'/image/project/detailProducts/Line/product3.jpg'},
                    {src:'/image/project/detailProducts/Line/product4.jpg'},
                    {src:'/image/project/detailProducts/Line/product5.jpg'},
                    {src:'/image/project/detailProducts/Line/product6.jpg'},
                ]},
            {title:"Fairmont Claremont",location:"41 Tunnel Rd, Berkeley, CA 94705, United States",id:'Fairmont',
                img:[{src:'/image/project/detailProducts/Fairmont/product1.jpg'},
                    {src:'/image/project/detailProducts/Fairmont/product2.jpg'},
                    {src:'/image/project/detailProducts/Fairmont/product3.jpg'},
                    {src:'/image/project/detailProducts/Fairmont/product4.jpg'},
                    {src:'/image/project/detailProducts/Fairmont/product5.jpg'},
                ]},
            {title:"Marriott Dallas Texas",location:"650 North Pearl Street, Dallas, Texas 75201 USA",id:'Marriott',
                img:[{src:'/image/project/detailProducts/Marriott/product1.jpg'},
                    {src:'/image/project/detailProducts/Marriott/product2.jpg'},
                    {src:'/image/project/detailProducts/Marriott/product3.jpg'},
                ]},
            {title:"Conrad Miami",location:"1395 Brickell Ave, Miami, FL 33131, USA",id:'Conrad',
                img:[{src:'/image/project/detailProducts/Conrad/product1.jpg'},
                    {src:'/image/project/detailProducts/Conrad/product2.jpg'},
                    {src:'/image/project/detailProducts/Conrad/product3.jpg'},
                    {src:'/image/project/detailProducts/Conrad/product4.jpg'},
                    {src:'/image/project/detailProducts/Conrad/product5.jpg'},
                    {src:'/image/project/detailProducts/Conrad/product6.jpg'},
                    {src:'/image/project/detailProducts/Conrad/product7.jpg'},
                    {src:'/image/project/detailProducts/Conrad/product8.jpg'},
                ]},
            {title:"Tampa Marriott Waterside",location:"505 Water St, Tampa, FL 33602, United States",id:'Tampa',
                img:[{src:'/image/project/detailProducts/Tampa/product1.jpg'},
                    {src:'/image/project/detailProducts/Tampa/product2.jpg'},
                    {src:'/image/project/detailProducts/Tampa/product3.jpg'},
                    {src:'/image/project/detailProducts/Tampa/product4.jpg'},
                    {src:'/image/project/detailProducts/Tampa/product5.jpg'},
                    {src:'/image/project/detailProducts/Tampa/product6.jpg'},
                ]},
            {title:"Godfrey Illinois",location:"127 W HURON STREET, CHICAGO, IL, 60654",id:'Godfrey',
                img:[{src:'/image/project/detailProducts/Godfrey/product1.jpg'},
                    {src:'/image/project/detailProducts/Godfrey/product2.jpg'},
                    {src:'/image/project/detailProducts/Godfrey/product3.jpg'},
                    {src:'/image/project/detailProducts/Godfrey/product4.jpg'},
                    {src:'/image/project/detailProducts/Godfrey/product5.jpg'},
                ]},
            {title:"Hilton Grand Islander @",location:"2023 Kalia Road, Honolulu, Hawaii 96815, USA",id:'Hilton',
                img:[{src:'/image/project/detailProducts/Hilton/product1.jpg'},
                    {src:'/image/project/detailProducts/Hilton/product2.jpg'},
                ]},
        ],
        data4:[
            {alt: 'king1',id:'king1',name:'Hotel Guest Room Bed Set',minPrice:315, maxPrice:545,
                img: [{src: '/image/ReferencePrice/BedBase/Detail/king1/king1.jpg'},
                      {src: '/image/ReferencePrice/BedBase/Detail/king1/king2.jpg'},
                      {src: '/image/ReferencePrice/BedBase/Detail/king1/king3.jpg'},
                      {src: '/image/ReferencePrice/BedBase/Detail/king1/king4.jpg'}
                ]
             },
            {alt: 'king2',id:'king2',name:'Hotel Guestroom Bed Set - Headboard & Bedbase',minPrice:275, maxPrice:495,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/king2.jpg'}]
            },
            {alt: 'king3',id:'king3',name:'Hotel Guestroom Bed Set - Headboard & Bedbase',minPrice:345, maxPrice:575,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/king3.jpg'}]
            },
            {alt: 'king4',id:'king4',name:'Hotel Guestroom Bed Set - Headboard & Bedbase',minPrice:295, maxPrice:615,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/king4.jpg'}]
            },
            {alt: 'king5',id:'king5',name:'King Headboard - Hilton Myrtle Beach Resort',minPrice:345, maxPrice:525,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/king5.jpg'}]
            },
            {alt: 'king6',id:'king6',name:'King Headboard Premiere Suite - Hyatt Regency Morristown',minPrice:445, maxPrice:765,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/king6.jpg'}]
            },
            {alt: 'king7',id:'king7',name:'King Headboard',minPrice:275, maxPrice:535,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/king7.jpg'}]
            },
            {alt: 'king8',id:'king8',name:'King Headboard - Choctaw Durant',minPrice:345, maxPrice:625,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/king8.jpg'}]
            },
            {alt: 'king9',id:'king9',name:'King Headboard',minPrice:315, maxPrice:555,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/king10.jpg'}]
            },
            {alt: 'king11',id:'king11',name:'King Headboard',minPrice:245, maxPrice:550,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/king11.jpg'}]
            },
            {alt: 'king12',id:'king12',name:'King Headboard - 54117',minPrice:145, maxPrice:425,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/king12.jpg'}]
            },
            {alt: 'queen1',id:'queen1',name:'Double Queen Headboard',minPrice:345, maxPrice:715,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/queen1.jpg'}]
            },
            {alt: 'queen2',id:'queen2',name:'Double Queen Headboard',minPrice:365, maxPrice:735,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/queen2.jpg'}]
            },
            {alt: 'queen3',id:'queen3',name:'Double Queen Headboard',minPrice:345, maxPrice:675,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/queen3.jpg'}]
            },
            {alt: 'queen4',id:'queen4',name:'Double Queen Headboard',minPrice:365, maxPrice:745,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/queen4.jpg'}]
            },
            {alt: 'queen5',id:'queen5',name:'Double Queen Headboard',minPrice:335, maxPrice:755,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/queen5.jpg'}]
            },
            {alt: 'queen6',id:'queen6',name:'Double Queen Headboard',minPrice:375, maxPrice:725,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/queen6.jpg'}]
            },
            {alt: 'bed1',id:'bed1',name:'Hotel Guest Room Bed Set',minPrice:645, maxPrice:955,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/bed1.jpg'}]
            },
            {alt: 'bed2',id:'bed2',name:'Hotel Guestroom Bed Set - Headboard & Bedbase',minPrice:635, maxPrice:955,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/bed2.jpg'}]
            },
            {alt: 'bed3',id:'bed3',name:'Hotel Guest Room Bed Set - Headboard & Bedroom',minPrice:625, maxPrice:875,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/bed3.jpg'}]
            },
            {alt: 'bed4',id:'bed4',name:'Hotel Guest Room Bed Set - Headboard & Bedbase',minPrice:750, maxPrice:1150,
                img:[{src: '/image/ReferencePrice/BedBase/Detail/bed4.jpg'}]
            },
            {cabinet:[]},
            {closet:[]},
            {tv:[]},
            {nightstand:[]},
            {table:[]},
            {sofa:[]},
            {vanity:[]},
        ]
        }
    ]
    })